"""Assemble Block Kit message and deliver to Slack."""

import logging
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

from jarvis.core.exceptions import SlackDeliveryError

__all__ = ["PluginSummary", "build_message", "post_message", "write_markdown_file"]

log = logging.getLogger(__name__)


_TABLE_SEP_RE = re.compile(r"^\s*\|[-: |]+\|\s*$")


def _md_to_mrkdwn(text: str) -> str:
    """Convert GitHub-flavored markdown to Slack mrkdwn.

    Slack mrkdwn differences from standard markdown:
    - No heading syntax (### etc.) — use *bold* as a substitute
    - Bold is *text*, not **text**
    - Tables are not rendered — wrap them in a code fence instead
    """
    # ### Headings → *bold heading*
    text = re.sub(r"^#{1,6}\s+(.+)$", r"*\1*", text, flags=re.MULTILINE)
    # **bold** → *bold*
    text = re.sub(r"\*\*(.+?)\*\*", r"*\1*", text)
    # - list items → • bullets (Slack doesn't auto-render markdown lists)
    # Handles indented bullets (e.g. "  - item") as well as top-level ones
    text = re.sub(r"^(\s*)- ", r"\1• ", text, flags=re.MULTILINE)
    # Markdown tables → code-fenced plain table (strip separator rows)
    lines = text.split("\n")
    out: list[str] = []
    i = 0
    while i < len(lines):
        if (
            lines[i].strip().startswith("|")
            and i + 1 < len(lines)
            and _TABLE_SEP_RE.match(lines[i + 1])
        ):
            out.append("```")
            while i < len(lines) and lines[i].strip().startswith("|"):
                if not _TABLE_SEP_RE.match(lines[i]):
                    out.append(lines[i])
                i += 1
            out.append("```")
        else:
            out.append(lines[i])
            i += 1
    return "\n".join(out)


@dataclass(slots=True)
class PluginSummary:
    display_name: str
    markdown: str
    ok: bool
    links: list[str] = field(default_factory=list)


def build_message(
    summaries: list[PluginSummary],
    run_duration_s: float,
    model: str,
    total_tokens: int,
    exec_summary: str | None = None,
) -> list[dict]:
    """Assemble a Slack Block Kit block list from per-plugin summaries."""
    date_str = datetime.now(timezone.utc).strftime("%A, %B %-d %Y")
    ok_count = sum(1 for s in summaries if s.ok)
    fail_count = len(summaries) - ok_count

    blocks: list[dict] = [
        {
            "type": "header",
            "text": {"type": "plain_text", "text": f"Jarvis — Morning Brief — {date_str}"},
        },
        {
            "type": "context",
            "elements": [
                {
                    "type": "mrkdwn",
                    "text": (
                        f"Run completed in {run_duration_s:.1f}s · "
                        f"{ok_count} plugins succeeded · "
                        f"{fail_count} failed"
                    ),
                }
            ],
        },
        {"type": "divider"},
    ]

    if exec_summary:
        blocks.append({"type": "section", "text": {"type": "mrkdwn", "text": _md_to_mrkdwn(exec_summary)}})
        blocks.append({"type": "divider"})

    for summary in summaries:
        text = _md_to_mrkdwn(summary.markdown) if summary.ok else f"_{summary.display_name}: unavailable_"
        blocks.append({"type": "section", "text": {"type": "mrkdwn", "text": text}})
        blocks.append({"type": "divider"})

    blocks.append(
        {
            "type": "context",
            "elements": [
                {
                    "type": "mrkdwn",
                    "text": f"Generated by Groq · {model} · {total_tokens:,} tokens",
                }
            ],
        }
    )

    return blocks


def write_markdown_file(
    summaries: list[PluginSummary],
    run_duration_s: float,
    model: str,
    total_tokens: int,
    exec_summary: str | None = None,
    output_path: str | None = None,
    output_dir: str = ".",
) -> str:
    """Write the digest to a markdown file and return the path written.

    If `output_path` is set it is used as-is. Otherwise the file is written to
    `output_dir` with a date-stamped name.
    """
    date_str = datetime.now(timezone.utc).strftime("%A, %B %-d %Y")
    ok_count = sum(1 for s in summaries if s.ok)
    fail_count = len(summaries) - ok_count

    if output_path:
        path = Path(output_path)
    else:
        filename = f"jarvis-brief-{datetime.now(timezone.utc).strftime('%Y-%m-%d')}.md"
        path = Path(output_dir) / filename

    path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        f"# Jarvis — Morning Brief — {date_str}",
        "",
        f"_Run completed in {run_duration_s:.1f}s · {ok_count} plugins succeeded · {fail_count} failed_",
        "",
        "---",
        "",
    ]

    if exec_summary:
        lines += [exec_summary, "", "---", ""]

    for summary in summaries:
        lines.append(summary.markdown if summary.ok else f"_{summary.display_name}: unavailable_")
        lines += ["", "---", ""]

    lines.append(f"_Generated by Groq · {model} · {total_tokens:,} tokens_")

    path.write_text("\n".join(lines))

    log.info("Digest written to %s", path)
    return str(path)


async def post_message(
    blocks: list[dict],
    bot_token: str,
    target_type: str,
    target_id: str,
    username: str,
    icon_emoji: str,
) -> None:
    """Post blocks to Slack, falling back to stdout on failure."""
    import json

    from slack_sdk.errors import SlackApiError
    from slack_sdk.web.async_client import AsyncWebClient

    client = AsyncWebClient(token=bot_token)

    channel = target_id
    if target_type == "user":
        try:
            resp = await client.conversations_open(users=[target_id])
            channel = resp["channel"]["id"]
        except SlackApiError as exc:
            log.exception("Failed to open DM with user %s", target_id)
            raise SlackDeliveryError(str(exc)) from exc

    try:
        await client.chat_postMessage(
            channel=channel,
            blocks=blocks,
            username=username,
            icon_emoji=icon_emoji,
        )
        log.info("Posted digest to Slack channel/DM %s", channel)
    except SlackApiError as exc:
        log.exception("Slack postMessage failed — falling back to stdout")
        print(json.dumps(blocks, indent=2))
        raise SlackDeliveryError(str(exc)) from exc
