"""Assemble Block Kit message and deliver to Slack."""

import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone

from jarvis.core.exceptions import SlackDeliveryError

__all__ = ["PluginSummary", "build_message", "post_message", "write_markdown_file"]

log = logging.getLogger(__name__)


@dataclass(slots=True)
class PluginSummary:
    display_name: str
    markdown: str
    ok: bool
    links: list[str] = field(default_factory=list)


def build_message(
    summaries: list[PluginSummary],
    run_duration_s: float,
    model: str,
    total_tokens: int,
) -> list[dict]:
    """Assemble a Slack Block Kit block list from per-plugin summaries."""
    date_str = datetime.now(timezone.utc).strftime("%A, %B %-d %Y")
    ok_count = sum(1 for s in summaries if s.ok)
    fail_count = len(summaries) - ok_count

    blocks: list[dict] = [
        {
            "type": "header",
            "text": {"type": "plain_text", "text": f"Jarvis — Morning Brief — {date_str}"},
        },
        {
            "type": "context",
            "elements": [
                {
                    "type": "mrkdwn",
                    "text": (
                        f"Run completed in {run_duration_s:.1f}s · "
                        f"{ok_count} plugins succeeded · "
                        f"{fail_count} failed"
                    ),
                }
            ],
        },
        {"type": "divider"},
    ]

    for summary in summaries:
        text = summary.markdown if summary.ok else f"_{summary.display_name}: unavailable_"
        blocks.append({"type": "section", "text": {"type": "mrkdwn", "text": text}})
        if summary.links:
            link_text = " · ".join(f"<{url}|link>" for url in summary.links[:5])
            blocks.append(
                {"type": "context", "elements": [{"type": "mrkdwn", "text": link_text}]}
            )
        blocks.append({"type": "divider"})

    blocks.append(
        {
            "type": "context",
            "elements": [
                {
                    "type": "mrkdwn",
                    "text": f"Generated by Groq · {model} · {total_tokens:,} tokens",
                }
            ],
        }
    )
    return blocks


def write_markdown_file(
    summaries: list[PluginSummary],
    run_duration_s: float,
    model: str,
    total_tokens: int,
    output_path: str | None = None,
) -> str:
    """Write the digest to a markdown file and return the path written."""
    date_str = datetime.now(timezone.utc).strftime("%A, %B %-d %Y")
    ok_count = sum(1 for s in summaries if s.ok)
    fail_count = len(summaries) - ok_count

    path = output_path or f"jarvis-brief-{datetime.now(timezone.utc).strftime('%Y-%m-%d')}.md"

    lines = [
        f"# Jarvis — Morning Brief — {date_str}",
        "",
        f"_Run completed in {run_duration_s:.1f}s · {ok_count} plugins succeeded · {fail_count} failed_",
        "",
        "---",
        "",
    ]

    for summary in summaries:
        lines.append(summary.markdown if summary.ok else f"_{summary.display_name}: unavailable_")
        if summary.links:
            for url in summary.links[:5]:
                lines.append(f"- {url}")
        lines += ["", "---", ""]

    lines.append(f"_Generated by Groq · {model} · {total_tokens:,} tokens_")

    with open(path, "w") as f:
        f.write("\n".join(lines))

    log.info("Digest written to %s", path)
    return path


async def post_message(
    blocks: list[dict],
    bot_token: str,
    target_type: str,
    target_id: str,
    username: str,
    icon_emoji: str,
) -> None:
    """Post blocks to Slack, falling back to stdout on failure."""
    import json

    from slack_sdk.errors import SlackApiError
    from slack_sdk.web.async_client import AsyncWebClient

    client = AsyncWebClient(token=bot_token)

    channel = target_id
    if target_type == "user":
        try:
            resp = await client.conversations_open(users=[target_id])
            channel = resp["channel"]["id"]
        except SlackApiError as exc:
            log.exception("Failed to open DM with user %s", target_id)
            raise SlackDeliveryError(str(exc)) from exc

    try:
        await client.chat_postMessage(
            channel=channel,
            blocks=blocks,
            username=username,
            icon_emoji=icon_emoji,
        )
        log.info("Posted digest to Slack channel/DM %s", channel)
    except SlackApiError as exc:
        log.exception("Slack postMessage failed — falling back to stdout")
        print(json.dumps(blocks, indent=2))
        raise SlackDeliveryError(str(exc)) from exc
